### ISSUE TITLE
train bug,gpu bug

### ISSUE THREAD

**Issue by dempsey888** [tteepe/GaitGraph#3]
when I trained the model,I use 8 gpus [0,1,2,3,4,5,6,7] . But only gpu0 is utilization,the utilization rate of other gpu is 0.  I am looking forward your reply,thank you very much!

**Comment by tteepe** [comment]
Hi,

since the network and the dataset are rather small we never really implement Multi-GPU support.
But I added the required code lines in https://github.com/tteepe/GaitGraph/commit/7e655251657bf4ca189e712cf01df39a390eac69

Could you pull the new files and let me know if it works? All my multi-GPU machines are currently busy :)

**Comment by guoxianda** [comment]
thank you for your reply. I have solved this problem by adding code 'model = torch.nn.DataParallel(model)' before 'model.cuda()'.It works for me.
